Router.map ->
	@route "logo", path: "/"
	@route "cordovaLogin"
	@route "webLogin"
	@route "home"
	@route "fight", path: "fight/:data?"
	@route "cardList"
	@route "myCards"
	@route "compoundCard"
	@route "selectOneCard"
	@route "selectMultiCard"
	@route "shop"
